resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

elasticsearch:
  auth:
    enabled: true
    user: elastic
    existingSecret:
      name: es-credentials
      key: ES_PASSWORD
  includeTagKey: true
  setOutputHostEnvVar: true
  # If setOutputHostEnvVar is false the hosts value is ignored
  # If you are configuring an AWS signing sidecar, hosts should be the network
  # address of the sidecar, like "localhost:8080"
  hosts: ["stav-devops.es.us-east-1.aws.found.io:443"]
  indexName: "fluentd"
  logstash:
    enabled: true
    prefix: "logstash"
    prefixSeparator: "-"
    dateformat: "%Y.%m.%d"
  ilm:
    enabled: false
    policy_id: logstash-policy
    policy: {}
      # example for ilm policy config
      # phases:
      #   hot:
      #     min_age: 0ms
      #     actions:
      #       rollover:
      #         max_age: 30d
      #         max_size: 20gb
      #       set_priority:
      #           priority: 100
      #   delete:
      #     min_age: 60d
      #     actions:
      #       delete:
    policies: {}
      # example for ilm policies config
      # ilm_policy_id1: {}
      # ilm_policy_id2: {}
    policy_overwrite: false
  template:
    enabled: false
    overwrite: false
    useLegacy: true
    name: fluentd-template
    file: fluentd-template.json
    content: |-
      {
        "index_patterns": [
            "logstash-*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "1"
            }
        }
      }

  path: ""
  # If you are configuring an AWS signing sidecar, scheme should be "http"
  scheme: "https"
  sslVerify: true
  sslVersion: "TLSv1_2"
  outputType: "elasticsearch"
  typeName: "_doc"
  logLevel: "debug"
  log400Reason: true
  reconnectOnError: true
  reloadOnFailure: false
  reloadConnections: false
  requestTimeout: "5s"
  suppressTypeName: false
  includeTimestamp: false
  buffer:
    enabled: true
    # ref: https://docs.fluentd.org/configuration/buffer-section#chunk-keys
    chunkKeys: ""
    type: "file"
    path: "/var/log/fluentd-buffers/kubernetes.system.buffer"
    flushMode: "interval"
    retryType: "exponential_backoff"
    flushThreadCount: 2
    flushInterval: "5s"
    retryForever: true
    retryMaxInterval: 30
    chunkLimitSize: "2M"
    totalLimitSize: "512M"
    overflowAction: "block"

# If you want to change args of fluentd process
# by example you can add -vv to launch with trace log
fluentdArgs: "--no-supervisor -q"

# Specifies the output format of fluentd's own log messages. Set to
# "json" to enable structured logging.
# See https://docs.fluentd.org/deployment/logging#log-format
fluentdLogFormat: "json"

# If you want to add custom environment variables from secrets, use the secret list
secret:
- name: FLUENT_ELASTICSEARCH_PASSWORD
  secret_name: es-credentials
  secret_key: ES_PASSWORD
- name: FLUENT_ELASTICSEARCH_USER
  secret_name: es-credentials
  secret_key: ES_USERNAME

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: false
  interval: 10s
  path: /metrics
  port: 24231
  type: ClusterIP

serviceMetric:
  ## If true, the metrics service will be created
  ## Alternative to implicit creation through serviceMonitor.enabled
  ##
  enabled: true