apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: {{ include "namespace-on-boarding.name" . }}
  labels:
    {{- include "namespace-on-boarding.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployer
  namespace: {{ include "namespace-on-boarding.name" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: {{ include "namespace-on-boarding.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: {{ include "namespace-on-boarding.name" . }}