{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "flask-sample.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-sample.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flask-sample.name" . }}
  minReplicas: {{ .Values.autoscaling.minPods }}
  maxReplicas: {{ .Values.autoscaling.maxPods }}
  metrics:
    {{- if .Values.autoscaling.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpu.percentage }}
    {{- end }}
    {{- if .Values.autoscaling.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.memory.percentage }}
    {{- end }}
    {{- range $v := .Values.autoscaling.customMetrics }}
    - type: Pods
      pods:
        metricName: {{ $v.name }}
        targetAverageValue: {{ $v.threshold }}
    {{- end }}
{{- end }}