apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-sample.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-sample.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.microservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flask-sample.selectorLabels" . | nindent 4 }}