# Global variables
microservice:
  name: flask-sample
  tag: 1.0.0
  environment: dev
  port: 3000
  healthCheckPath: /hello

resources:
  memory: 128Mi
  cpu: 100m

autoscaling:
  enabled: false
  minPods: 1
  maxPods: 10
  cpu:
    enabled: false
    percentage: 90
  memory:
    enabled: false
    percentage: 70
  customMetrics: []
  ###
  ### customMetrics:
  ### - name: sessions_counter
  ###   threshold: 2
  ###

prometheusMetrics:
  enabled: true

# Image variables
registryBasePath: 882709358319.dkr.ecr.us-east-1.amazonaws.com

# If enableing ingress, the external URL will be https://{{ microservice.name }}-{{ microservice.environment }}.k8s.stavco9.com
ingress:
  enabled: true